apiVersion: apps/v1
kind: Deployment
metadata:
  name: dentist2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dentist2
  template:
    metadata:
      labels:
        app: dentist2
    spec:
      containers:
        - name: dentist2-container
          image: nicholasevrard/dentist2:latest
          ports:
            - containerPort: 80
