apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: nicholasevrard/dentiste:latest # <- nom de l’image sur Docker Hub une fois poussée
        ports:
        - containerPort: 80
